CREATE TABLE ChatSession (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ClientId BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ClosedAt DATETIME NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
    OperationalAddressId BIGINT NOT NULL,
    ChatClientSessionId BIGINT NOT NULL,
);

CREATE TABLE ChatMessageManualNote (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ChatSessionId BIGINT NOT NULL,
    SenderId BIGINT NOT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE ChatClientSession (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ClientId BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ClosedAt DATETIME NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE ChatParticipant (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ChatSessionId BIGINT NOT NULL,
    ParticipantType VARCHAR(100) NOT NULL,
    ParticipantId BIGINT NOT NULL,
    JoinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsRemoved BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (ChatSessionId) REFERENCES ChatSession(Id)
    -- AdminId and ProviderId foreign keys can be enforced in code
);

CREATE TABLE ChatMessage (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ChatSessionId BIGINT NOT NULL,
    SenderType VARCHAR(100) NOT NULL,
    SenderId BIGINT NOT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsInternalNote BOOLEAN NOT NULL DEFAULT FALSE,
    IsSeen BOOLEAN NOT NULL DEFAULT FALSE,
    Type VARCHAR(100) NOT NULL
);

CREATE TABLE ChatMessageNote (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    MessageNoteType VARCHAR(100) NOT NULL
);

CREATE TABLE ChatMention (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ChatMessageId BIGINT NOT NULL,
    ClientId BIGINT NOT NULL,
    OperationalAddressId BIGINT NOT NULL,
    MentionedType VARCHAR(100) NOT NULL,
    MentionedId BIGINT NOT NULL
);

CREATE TABLE ChatNotification (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ChatMentionId BIGINT NOT NULL,
    IsSeen BOOLEAN NOT NULL DEFAULT FALSE,
    NotifiedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
